#
# Created by: Jeff Wilson <jeff@jeffalwilson.com>
#

presets:
  global:
    # Make there's 10GB free before adding more downloads
    free_space:
      path: /mnt/storage
      space: 10000
    # Make sure all filenames are Windows safe (for samba)
    pathscrub: windows
    # Most of these are the results of problem torrents I kept seeing still pop up, so I wholesale blocked them
    # RegExr (http://www.gskinner.com/RegExr/) is a great tool for testing regexes
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b: {from: title}                    # Block any subbed/dubbed/etc videos
        - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title} # Block series, only accept one at a time
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bR5\b: {from: title}                               # The following are poor quality types that somehow got through the quality
        - \bWEBSCR\b: {from: title}                           # features usually due to the title including a keyword like "720p" as well
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
    torrent_alive: 20 # Require at least 20 seeds of any torrent
    # Filter by filenames. Allow multiple video types and rar packs (but note if there is just a
    # single .rar file it won't be accepted)
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
    # Limit the frequency of requests to domains so they don't complain about using a bot
    domain_delay:
      bt-chat.com: 5 seconds
      torrentz.eu: 5 seconds
    deluge: yes

  rssout:
    make_rss:
      file: ~/downloaded.rss
      days: 1

  # This preset is a "global" preset for all TV-related feeds.
  # We keep all of the RSS feeds that list tv-related torrents here
  # as well as where to check existing shows.
  tv-global:
    # This is a TON of feeds, you probably don't need so many, but why not?
    inputs:
      - rss: { url: 'http://rss.bt-chat.com/?group=3', silent: yes }            # BT-Chat (EZTV)
      - rss: { url: 'http://www.torlock.com/television/rss.xml', silent: yes }  # TorLock (TV)
      - rss: { url: 'http://torrentz.eu/feed_verified?q=tv', silent: yes }      # Torrentz (Verified only, TV)
      - rss: { url: 'http://ezrss.it/feed/', silent: yes }                      # EZRSS
      - rss: { url: 'http://showrss.karmorra.info/rss.php?user_id=108961&hd=2&proper=1', silent: yes } # Karmorra (personal)
    # Impose reasonable size constraints
    content_size:
      max: 8000
      min: 20
    # Prevent from downloading shows that were aquired manually
    # or are currently downloading
    exists_series:
      - "/mnt/storage/series/"
      - "/mnt/storage/animations/"
      - "/mnt/storage/documentaries/"
      - "/mnt/tampon/torrent/loading/"
      - "/mnt/tampon/torrent/complete/"
    # Look up info on TheTVDB.com to fill in extra info
    thetvdb_lookup: yes
    # Add accepted entries to Deluge and make sure they end up in the correct folder with a nice name
    set:
      # Rename the "content file" to something nice
      content_filename: >
        {{ series_name|replace('/', '_')|replace(':', ' -') }} - {% if series_id_type == 'ep' and thetvdb_lookup_season_offset|default(False) %}{{ "S%0.2dE%0.2d"|format((series_season + thetvdb_lookup_season_offset),series_episode) }}{% else %}{{ series_id }}{% endif %}{% if ep_name|default(False) %} - {{ ep_name|replace('/', '_')|replace(':', ' -') }}{% endif %} - {{ quality }}
      label: tv

  # These are the shows I regularly watch
  tv-shows:
    # I've broken out my series lists into a seperate yml to clean up my config
    include: [ series.yml ]
    # Add accepted entries to Deluge, queue them to the top and make sure they end up in the correct folder
    set:
      movedone: /mnt/storage/new/
      queuetotop: yes

  # I'm always up for new shows, but some I genres I just can't stand. This preset
  # grabs all of the premieres except for some genres
  tv-premieres:
    # The entry has to have the series_genres field so I can filter by it
    require_field:
      - series_genres
      - ep_air_date
    # Block these genres if they exist in the list of series_genres at all
    regexp:
      reject:
        - talk show: {from: series_genres}
        - game show: {from: series_genres}
        - reality: {from: series_genres}
        - children: {from: series_genres}
        - home and garden: {from: series_genres}
    if:
      # Block these genres only if they are the ONLY genre listed in series_genres
      # For example, this will not block a show that's both "Comedy" and "Drama" but it will
      # block a show that is just "Drama"
      - "series_genres == ['Drama']": reject
      - "series_genres == ['Comedy']": reject
      # Block premieres that weren't within the last 60 days
      - ep_air_date != None and ep_air_date < now - timedelta(days=60): reject
    # Accept all series permieres, 1080p first, then minimum of 720p after 8 hours
    series_premiere:
      quality: hdtv+ <=1080p !10bit
      target: <720p
      timeframe: 6 hours
      propers: 12 hours
    # Add to deluge, but don't queue to top (My_TV_Shows are more important) and put in a different
    # location
    set:
      movedone: /mnt/storage/premiere/
      queuetotop: no
      label: tv-premiere

# This is where we pull everything together
tasks:
  # All of the TV-related feeds pull in the tv-global preset, this gives
  # all of the necessary rss sources and a few extra configs

  # There are 3 My_TV Shows feeds, the first, tries to get the most wanted qualities
  TV_Shows:
    priority: 10
    preset:
      - tv-global
      - tv-shows
      - rssout

  # Feed for the tv-premieres plugin
  Series_Premieres:
    priority: 40
    preset:
      - tv-global
      - tv-premieres
      - rssout

  emailfeed:
    interval: 1 days
    rss:
      url: /~/downloaded.rss
    disable_builtins: [seen]
    accept_all: yes
    include: [ private/smtp.yml ]
