presets:
  global:
    # Make there's 10GB free before adding more downloads
    free_space:
      path: /mnt/storage
      space: 10000
    # Make sure all filenames are Windows safe (for samba)
    pathscrub: windows
    # Most of these are the results of problem torrents I kept seeing still pop up, so I wholesale blocked them
    # RegExr (http://www.gskinner.com/RegExr/) is a great tool for testing regexes
    regexp:
      reject:
        #- (s|d)ub(s|bed)?\b: {from: title}                    # Block any subbed/dubbed/etc videos
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bR5\b: {from: title}                               # The following are poor quality types that somehow got through the quality
        - \bWEBSCR\b: {from: title}                           # features usually due to the title including a keyword like "720p" as well
        - \bscreener\b: {from: title}
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - \bRAW\b: {from: title}
        - \bfrench\b: {from: title}
        - \bgerman\b: {from: title}
        - \bita\b: {from: title}
        - \bspanish\b: {from: title}
        - \bvostfr\b: {from: title}
    #torrent_alive: { min_seeds: 1, reject_for: 10 minutes }
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
        - '*.rar'
        - '*.r0*'
        - '*.part0*'
      reject: [ 'password.txt' ]
    # Limit the frequency of requests to domains so they don't complain about using a bot
    domain_delay:
      bt-chat.com: 5 seconds
      torrentz.eu: 5 seconds
      kat.ph: 5 seconds
      ezrss.it: 5 seconds
    deluge:
      main_file_only: yes
      user: local
      pass: lacol
      addpaused: yes
      queuetotop: no
      path: /mnt/tampon/torrent/loading/
  rssout:
    make_rss:
      file: ~/downloaded_missing.rss
      days: 1

  tv-global:
    discover:
      what:
        - listdir:
          - '/mnt/storage/series/'
          - '/mnt/storage/animations/'
          - '/mnt/storage/documentaries/'
          - '/mnt/storage/missing/'
      from:
        - search_rss: https://www.ezrss.it/search/index.php?show_name={{search_term}}&mode=rss
        - search_rss: http://torrentz.eu/feed?q={{search_term}}
        - search_rss: http://www.kat.ph/usearch/{{search_term}}/?field=time_add&sorder=desc&rss=1
        - torrentz: good
      type: any
    # Impose reasonable size constraints
    content_size:
      min: 20
    # Prevent from downloading shows that were aquired manually
    # or are currently downloading
    exists_series:
      - '/mnt/storage/new/'
      - '/mnt/storage/toSort/'
      - '/mnt/storage/series/'
      - '/mnt/storage/animations/'
      - '/mnt/storage/documentaries/'
      - '/mnt/tampon/torrent/loading/'
      - '/mnt/tampon/torrent/complete/'
    # Look up info on TheTVDB.com to fill in extra info
    thetvdb_lookup: no
    # Add accepted entries to Deluge and make sure they end up in the correct folder with a nice name
    set:
      # Rename the "content file" to something nice, deluge specific
      content_filename: >
        {{ series_name|replace('/', '_')|replace(':', ' -') }} - {% if series_id_type == 'ep' and thetvdb_lookup_season_offset|default(False) %}{{ "S%0.2dE%0.2d"|format((series_season + thetvdb_lookup_season_offset),series_episode) }}{% else %}{{ series_id }}{% endif %}{% if ep_name|default(False) %} - {{ ep_name|replace('/', '_')|replace(':', ' -') }}{% endif %} - {{ quality }}
      label: missing

  # These are the shows I regularly watch
  tv-shows:
    # I've broken out my series lists into a seperate yml to clean up my config
    include: [ series_missing.yml ]
    # Add accepted entries to Deluge, queue them to the top and make sure they end up in the correct folder
    set:
      movedone: /mnt/storage/missing/

tasks:
  # All of the TV-related feeds pull in the tv-global preset, this gives
  # all of the necessary rss sources and a few extra configs

  # There are 3 My_TV Shows feeds, the first, tries to get the most wanted qualities
  missing:
    priority: 10
    preset:
      - tv-global
      - tv-shows
      - rssout

  emailfeed:
    interval: 1 days
    rss:
      url: file:///home/guillaume/downloaded_missing.rss
    disable_builtins: [seen]
    accept_all: yes
    include: [ private/smtp.yml ]
