cd /mnt/storage/
mkdir missing
cd missing
mkdir 'Accel World'
mkdir 'Albator 78'
mkdir 'Albator 84'
mkdir 'Avatar The Last Airbender'
mkdir 'Avatar The Legend of Aang'
mkdir 'Avatar The Legend of Korra'
mkdir 'City Hunter'
mkdir 'Cowboy Bebop'
mkdir 'Deadman Wonderland'
mkdir 'Escaflowne'
mkdir 'Naruto'
mkdir 'Naruto Shippuden'
mkdir 'Neon Genesis Evangelion'
mkdir 'One Piece'
mkdir 'Space Adventure Cobra'
mkdir 'Space Battleship Yamato'
mkdir 'Star Blazer'
mkdir 'Strait Jacket'
mkdir 'Vampire Hunter D'
mkdir 'WitchBlade'
mkdir 'Aeon Flux'
mkdir 'Babylon 5'
mkdir 'Babylon 5 Crusade'
mkdir 'Batman The Animated Series'
mkdir 'Buck Rogers in the 25th Century'
mkdir 'Caprica'
mkdir 'Dead Like Me'
mkdir 'Dollhouse'
mkdir 'Farscape'
mkdir 'Firefly'
mkdir 'Highlander'
mkdir 'Highlander The Raven'
mkdir 'Jericho'
mkdir 'Quantum Leap'
mkdir 'Sliders'
mkdir 'Star Trek Deep Space Nine'
mkdir 'Star Trek The Next Generation'
mkdir 'Star Trek The Original Series'
mkdir 'Stargate Universe'
mkdir 'Stargate Atlantis'
mkdir 'Space Above and Beyond'
mkdir 'The Penguins of Madagascar'
mkdir 'Terminator The Sarah Connor Chronicles'

